Fix: added compileAccumulatorLoop to have a CSP safe option
6pac/SlickGrid pull request #952
Opened 2023-12-21 09:52 UTC by JesperJakobsenCIM

2023-12-21 20:43 UTC, ghiscoding requested changes

2023-12-21 20:43 UTC, ghiscoding commented on src/slick.dataview.ts
> +        }else {
small lint nitpick, can you add space after curly brace and also add a space after bracket on the if condition.

2023-12-21 20:43 UTC, ghiscoding commented on src/slick.dataview.ts
> +    if (aggregator.accumulate) {
can you remove the extra line carriage above

2023-12-21 20:46 UTC, ghiscoding commented
Apart from some small Linting issues, the PR looks quite simple. Have you check logged perf? Just asking again in case there's no difference in perf, if so only 1 approach is enough. Remember that we kept the other separate because there was a slight perf decrease

2023-12-22 07:55 UTC, JesperJakobsenCIM commented
50 rows
![image](https://github.com/6pac/SlickGrid/assets/137038231/6f4df167-cdd5-4464-85ac-4731dade5f69)
Small test, first one is with CSP and second test is without CSP (old) method

By general the new method actually seems faster, surprisingly me a little and its even with quite a margin of performance

This is old method first and new method next with 5000 rows instead of 50
![image](https://github.com/6pac/SlickGrid/assets/137038231/58ae5413-8d56-4e60-876d-be88469ec65c)

2023-12-22 17:14 UTC, ghiscoding commented
it seems very similar and small diff, I would probably vote for keeping only the new one, what do you think?

2023-12-28 20:47 UTC, ghiscoding commented
@JesperJakobsenCIM so have you had a chance to compare if changing to a regular for loop makes a difference in performance? Do you think we should keep both function or merged into a single function? I'm waiting for your feedback before merging the PR. Thanks

2023-12-29 07:16 UTC, JesperJakobsenCIM commented
the 50.000 example is with a for loop, and it seems to get faster since 5.000 rows (without for loop) has the same speed as 50.000 rows with for loop

2023-12-29 07:19 UTC, ghiscoding commented
So does that mean that both functions are nearly the same speed? If so, can we keep only 1 function (the newest and CSP safe).

2023-12-29 07:21 UTC, JesperJakobsenCIM commented
its actually marginally faster
![image](https://github.com/6pac/SlickGrid/assets/137038231/9d603c49-72ee-43f0-8bbb-d0609c78dfde)
50.000 rows test
first 5 rows is CSP Safe and last 5 rows is old function

2023-12-29 07:23 UTC, ghiscoding commented
that is really awesome to see, faster is great 🚀 

So could refactor and keep only the CSP function then? I could merge it after and publish a new release, just waiting for this PR :)

2023-12-29 08:13 UTC, JesperJakobsenCIM commented
I've removed the old method and kept new method with its name for clarity.

2023-12-29 16:29 UTC, ghiscoding approved these changes

2023-12-29 16:32 UTC, merged

2023-12-29 20:40 UTC, ghiscoding commented
This is now available in the latest release [v5.7.0](https://github.com/6pac/SlickGrid/releases/tag/5.7.0), thanks again for your contributions. I think this was the last piece to be fully CSP Safe, thanks a lot for all your help and guidance on the subject 🎉

Happy Holidays 🎁